import { Logo, Car, Line } from "../../util/assets";
import {
  getDriverByNum,
  getDriverByKey,
  DriverKey,
} from "../pilots/driver/drivers-data";

export const getTeamByKey = (key) => {
  return Object.assign({}, Teams[key.toUpperCase()]);
};

export const Teams = {
  MERCEDES: {
    logo: Logo.mercedes,
    name: "Mercedes AMG Petronas",
    fullname: "Mercedes AMG Petronas",
    car: Car.mercedes,
    drivers: [
      getDriverByKey(DriverKey.lewis_hamilton),
      getDriverByKey(DriverKey.valtteri_bottas),
    ],
    base: "Брэкли, Великобритания",
    teamChief: "Тото Вольф",
    powerUnit: "Mercedes",
    chassis: "W11",
    firstTeamEntry: 1970,
    worldChampionships: "2014-2019",
    constructorsСup: "2014-2019",
    highestRaceFinish: "1 (x93)",
    polePositions: 103,
    fastestLaps: 66,
    info2019:
      "<p>2019</p>" +
      "<p>Начало сезона с беспрецедентной пятерки побед на первом-втором месте, и продолжение его еще дестью победами, гарантировало их шестой титул, удвоенный на отскоке. Всесторонняя командная работа является ключом к успеху даже чаще, чем максимальный темп. Валттери Боттас улучшил свой результат, а это означает, что Льюису Хэмилтону нужно приложить немало усилий, чтобы защитить свой титул чемпиона, что приближает британцев к рекорду всех времен Михаэля Шумахера.</p>",
    info2018:
      "<p>2018</p>" +
      "<p>Это сезон преимущественно о Льюисе Хэмилтоне, чьи 11 побед помогли сохранить пятый подряд чемпионский титул для команды - несмотря на соперников Ferrari, часто имеющих более быстрый автомобиль - продолжая свое доминирование в эпоху турбо-гибридов. Товарищ по команде Валттери Боттас заканчивает год без победы будучи вынужденным играть в тылу безудержного Гамильтона.</p>",
    info2017: "<p>2017</p>" + "<p>...</p>",
    info2016: "<p>2016</p>" + "<p>...</p>",
    line: "/docs/assets/images/lines/merline.png",
    images: [
      "/docs/assets/images/teams/mercedes/map1.jpg",
      "/docs/assets/images/teams/mercedes/map2.jpg",
      "/docs/assets/images/teams/mercedes/map3.jpg",
      "/docs/assets/images/teams/mercedes/map4.jpg",
      "/docs/assets/images/teams/mercedes/map5.jpg",
      "/docs/assets/images/teams/mercedes/map6.jpg",
      "/docs/assets/images/teams/mercedes/map7.jpg",
      "/docs/assets/images/teams/mercedes/map8.jpg",
      "/docs/assets/images/teams/mercedes/map9.jpg",
      "/docs/assets/images/teams/mercedes/map10.jpg",
      "/docs/assets/images/teams/mercedes/map11.jpg",
      "/docs/assets/images/teams/mercedes/map12.jpg",
      "/docs/assets/images/teams/mercedes/map13.jpg",
      "/docs/assets/images/teams/mercedes/map14.jpg",
      "/docs/assets/images/teams/mercedes/map15.jpg",
    ],
  },
  FERRARI: {
    logo: Logo.ferrari,
    name: "Scuderia Ferrari",
    fullname: "Scuderia Ferrari",
    car: Car.ferrari,
    drivers: [
      getDriverByKey(DriverKey.sebastian_vettel),
      getDriverByKey(DriverKey.charles_leclerc),
    ],
    base: "Маранелло, Италия",
    teamChief: "Маттиа Бинотто",
    powerUnit: "Ferrari",
    chassis: "SF1000",
    firstTeamEntry: 1950,
    worldChampionships:
      "1952, 1953, 1956, 1958, 1961, 1964, 1975, 1977, 1979, 2000-2004, 2007",
    constructorsСup:
      "1961, 1964, 1975-1977, 1979, 1982, 1983, 1999-2004, 2007, 2008",
    highestRaceFinish: "1 (x239)",
    polePositions: 221,
    fastestLaps: 253,
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/ferrari/fer1.jpg",
      "/docs/assets/images/teams/ferrari/fer2.jpg",
      "/docs/assets/images/teams/ferrari/fer3.jpg",
      "/docs/assets/images/teams/ferrari/fer4.jpg",
      "/docs/assets/images/teams/ferrari/fer5.jpg",
      "/docs/assets/images/teams/ferrari/fer6.jpg",
      "/docs/assets/images/teams/ferrari/fer7.jpg",
      "/docs/assets/images/teams/ferrari/fer8.jpg",
      "/docs/assets/images/teams/ferrari/fer9.jpg",
      "/docs/assets/images/teams/ferrari/fer10.jpg",
      "/docs/assets/images/teams/ferrari/fer11.jpg",
      "/docs/assets/images/teams/ferrari/fer12.jpg",
      "/docs/assets/images/teams/ferrari/fer13.jpg",
      "/docs/assets/images/teams/ferrari/fer14.jpg",
      "/docs/assets/images/teams/ferrari/fer15.jpeg",
    ],
  },
  RED_BULL: {
    logo: Logo.red_bull,
    name: "Red Bull",
    fullname: "Aston Martin Red Bull Racing",
    car: Car.red_bull,
    drivers: [
      getDriverByKey(DriverKey.max_verstappen),
      getDriverByKey(DriverKey.alexander_albon),
    ],
    base: "Милтон-Кинс, Великобритания",
    teamChief: "Кристиан Хорнер",
    powerUnit: "Honda",
    chassis: "RB16",
    firstTeamEntry: 1997,
    worldChampionships: "2010-2013",
    constructorsСup: "2010-2013",
    highestRaceFinish: "1 (x62)",
    polePositions: 62,
    fastestLaps: 65,
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/redbull/rbl1.jpg",
      "/docs/assets/images/teams/redbull/rbl2.jpg",
      "/docs/assets/images/teams/redbull/rbl3.jpg",
      "/docs/assets/images/teams/redbull/rbl4.jpg",
      "/docs/assets/images/teams/redbull/rbl5.jpg",
      "/docs/assets/images/teams/redbull/rbl6.jpg",
      "/docs/assets/images/teams/redbull/rbl7.jpg",
      "/docs/assets/images/teams/redbull/rbl8.jpg",
      "/docs/assets/images/teams/redbull/rbl9.jpg",
      "/docs/assets/images/teams/redbull/rbl10.jpg",
      "/docs/assets/images/teams/redbull/rbl11.jpg",
      "/docs/assets/images/teams/redbull/rbl12.jpg",
      "/docs/assets/images/teams/redbull/rbl13.jpg",
      "/docs/assets/images/teams/redbull/rbl14.jpg",
      "/docs/assets/images/teams/redbull/rbl15.jpg",
    ],
  },
  RENAULT: {
    logo: Logo.renault,
    name: "Renault DP World F1 Team",
    fullname: "Renault DP World F1 Team",
    car: Car.renault,
    drivers: [
      getDriverByKey(DriverKey.daniel_ricciardo),
      getDriverByKey(DriverKey.esteban_ocon),
    ],
    base: "Энстоун, Великобритания",
    teamChief: "Сирил Абитебул",
    powerUnit: "Renault",
    chassis: "R.S.20",
    firstTeamEntry: 1986,
    worldChampionships: "2005-2006",
    constructorsСup: "2005-2006",
    highestRaceFinish: "1 (x20)",
    polePositions: 20,
    fastestLaps: 13,
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/renault/ren1.jpg",
      "/docs/assets/images/teams/renault/ren2.jpg",
      "/docs/assets/images/teams/renault/ren3.jpg",
      "/docs/assets/images/teams/renault/ren4.jpg",
      "/docs/assets/images/teams/renault/ren5.jpg",
      "/docs/assets/images/teams/renault/ren6.jpg",
      "/docs/assets/images/teams/renault/ren7.jpg",
      "/docs/assets/images/teams/renault/ren8.jpg",
      "/docs/assets/images/teams/renault/ren9.jpg",
      "/docs/assets/images/teams/renault/ren10.jpg",
      "/docs/assets/images/teams/renault/ren11.jpg",
      "/docs/assets/images/teams/renault/ren12.jpg",
      "/docs/assets/images/teams/renault/ren13.jpg",
      "/docs/assets/images/teams/renault/ren14.jpg",
      "/docs/assets/images/teams/renault/ren15.jpg",
    ],
  },
  McLAREN: {
    logo: Logo.mclaren,
    name: "McLaren",
    fullname: "McLaren F1 Team",
    car: Car.mclaren,
    drivers: [
      getDriverByKey(DriverKey.carlos_sainz),
      getDriverByKey(DriverKey.lando_norris),
    ],
    base: "Уокинг, Великобритания",
    teamChief: "Зак Браун",
    powerUnit: "Renault",
    chassis: "MCL35",
    firstTeamEntry: 1966,
    worldChampionships: "1974, 1976, 1984-1986, 1988-1991, 1998, 1999, 2008",
    constructorsСup: "1974, 1984, 1985, 1988-1991, 1998",
    highestRaceFinish: "1 (x182)",
    polePositions: 155,
    fastestLaps: 155,
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/mclaren/mcl1.jpg",
      "/docs/assets/images/teams/mclaren/mcl2.jpg",
      "/docs/assets/images/teams/mclaren/mcl3.jpg",
      "/docs/assets/images/teams/mclaren/mcl4.jpg",
      "/docs/assets/images/teams/mclaren/mcl5.jpg",
      "/docs/assets/images/teams/mclaren/mcl6.jpg",
      "/docs/assets/images/teams/mclaren/mcl7.jpg",
      "/docs/assets/images/teams/mclaren/mcl8.jpg",
      "/docs/assets/images/teams/mclaren/mcl9.jpg",
      "/docs/assets/images/teams/mclaren/mcl10.jpg",
      "/docs/assets/images/teams/mclaren/mcl11.jpg",
      "/docs/assets/images/teams/mclaren/mcl12.jpg",
      "/docs/assets/images/teams/mclaren/mcl13.jpg",
      "/docs/assets/images/teams/mclaren/mcl14.jpg",
      "/docs/assets/images/teams/mclaren/mcl15.jpg",
    ],
  },
  ALPHA_TAURI: {
    logo: Logo.alpha_tauri,
    name: "Alpha Tauri",
    fullname: "Scuderia Alpha Tauri",
    car: Car.alpha_tauri,
    drivers: [
      getDriverByKey(DriverKey.daniil_kvyat),
      getDriverByKey(DriverKey.pier_gasli),
    ],
    base: "Фаэнца, Италия",
    teamChief: "Франц Тост",
    powerUnit: "Honda",
    chassis: "AT01",
    firstTeamEntry: 1985,
    worldChampionships: " ",
    constructorsСup: " ",
    highestRaceFinish: "1 (x1)",
    polePositions: 1,
    fastestLaps: 1,
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/alphatauri/alt1.jpg",
      "/docs/assets/images/teams/alphatauri/alt2.jpg",
      "/docs/assets/images/teams/alphatauri/alt3.jpg",
      "/docs/assets/images/teams/alphatauri/alt4.jpg",
      "/docs/assets/images/teams/alphatauri/alt5.jpg",
      "/docs/assets/images/teams/alphatauri/alt6.jpg",
      "/docs/assets/images/teams/alphatauri/alt7.jpg",
      "/docs/assets/images/teams/alphatauri/alt8.jpg",
      "/docs/assets/images/teams/alphatauri/alt9.jpg",
      "/docs/assets/images/teams/alphatauri/alt10.jpg",
      "/docs/assets/images/teams/alphatauri/alt11.jpg",
      "/docs/assets/images/teams/alphatauri/alt12.jpg",
      "/docs/assets/images/teams/alphatauri/alt13.jpg",
      "/docs/assets/images/teams/alphatauri/alt14.jpg",
      "/docs/assets/images/teams/alphatauri/alt15.jpg",
    ],
  },
  RACING_POINT: {
    logo: Logo.racing_point,
    name: "Racing Point",
    fullname: "BWT Racing Point Formula Team",
    car: Car.racing_point,
    drivers: [
      getDriverByKey(DriverKey.lance_stroll),
      getDriverByKey(DriverKey.sergio_perez),
    ],
    base: "Сильверстоун, Великобритания",
    Owner: "Лоуренс Стролл",
    teamChief: "Отмар Сафнауэр",
    powerUnit: "BWT Mercedes",
    chassis: "RP20",
    firstTeamEntry: 2019,
    worldChampionships: " ",
    constructorsСup: " ",
    highestRaceFinish: "4 (x1)",
    polePositions: " ",
    fastestLaps: " ",
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/racingpoint/rp1.jpg",
      "/docs/assets/images/teams/racingpoint/rp2.jpg",
      "/docs/assets/images/teams/racingpoint/rp3.jpg",
      "/docs/assets/images/teams/racingpoint/rp4.jpg",
      "/docs/assets/images/teams/racingpoint/rp5.jpg",
      "/docs/assets/images/teams/racingpoint/rp6.jpg",
      "/docs/assets/images/teams/racingpoint/rp7.jpg",
      "/docs/assets/images/teams/racingpoint/rp8.jpg",
      "/docs/assets/images/teams/racingpoint/rp9.jpg",
      "/docs/assets/images/teams/racingpoint/rp10.jpg",
      "/docs/assets/images/teams/racingpoint/rp11.jpg",
      "/docs/assets/images/teams/racingpoint/rp12.jpg",
      "/docs/assets/images/teams/racingpoint/rp13.jpg",
      "/docs/assets/images/teams/racingpoint/rp14.jpg",
      "/docs/assets/images/teams/racingpoint/rp15.jpg",
    ],
  },
  HAAS: {
    logo: Logo.haas,
    name: "Haas F1 Team",
    fullname: "Haas F1 Team",
    car: Car.haas,
    drivers: [
      getDriverByKey(DriverKey.romain_grosjean),
      getDriverByKey(DriverKey.kevin_magnussen),
    ],
    base: "Каннаполис, США",
    teamChief: "Гюнтер Штайнер",
    powerUnit: "Ferrari",
    chassis: "VF-20",
    firstTeamEntry: 2016,
    worldChampionships: " ",
    constructorsСup: " ",
    highestRaceFinish: "4 (x1)",
    polePositions: " ",
    fastestLaps: 1,
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/haas/haa1.jpg",
      "/docs/assets/images/teams/haas/haa2.jpg",
      "/docs/assets/images/teams/haas/haa3.jpg",
      "/docs/assets/images/teams/haas/haa4.jpg",
      "/docs/assets/images/teams/haas/haa5.jpg",
      "/docs/assets/images/teams/haas/haa6.jpg",
      "/docs/assets/images/teams/haas/haa7.jpg",
      "/docs/assets/images/teams/haas/haa8.jpg",
      "/docs/assets/images/teams/haas/haa9.jpg",
      "/docs/assets/images/teams/haas/haa10.jpg",
      "/docs/assets/images/teams/haas/haa11.jpg",
      "/docs/assets/images/teams/haas/haa12.jpg",
      "/docs/assets/images/teams/haas/haa13.jpg",
      "/docs/assets/images/teams/haas/haa14.jpg",
      "/docs/assets/images/teams/haas/haa15.jpg",
    ],
  },
  ALFA_ROMEO: {
    logo: Logo.alfa_romeo,
    name: "Alfa Romeo",
    fullname: "Alfa Romeo Racing",
    car: Car.alfa_romeo,
    drivers: [
      getDriverByKey(DriverKey.kimi_raikkonen),
      getDriverByKey(DriverKey.antonio_giovinazzi),
    ],
    base: "Хинвил, Швейцария",
    teamChief: "Фредерик Вассёр",
    powerUnit: "Ferrari",
    chassis: "C39",
    firstTeamEntry: 1993,
    worldChampionships: " ",
    constructorsСup: " ",
    highestRaceFinish: "1 (x1)",
    polePositions: 1,
    fastestLaps: 5,
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/alfaromeo/alr1.jpg",
      "/docs/assets/images/teams/alfaromeo/alr2.jpg",
      "/docs/assets/images/teams/alfaromeo/alr3.jpg",
      "/docs/assets/images/teams/alfaromeo/alr4.jpg",
      "/docs/assets/images/teams/alfaromeo/alr5.jpg",
      "/docs/assets/images/teams/alfaromeo/alr6.jpg",
      "/docs/assets/images/teams/alfaromeo/alr7.jpg",
      "/docs/assets/images/teams/alfaromeo/alr8.jpg",
      "/docs/assets/images/teams/alfaromeo/alr9.jpg",
      "/docs/assets/images/teams/alfaromeo/alr10.jpg",
      "/docs/assets/images/teams/alfaromeo/alr11.jpg",
      "/docs/assets/images/teams/alfaromeo/alr12.jpg",
      "/docs/assets/images/teams/alfaromeo/alr13.jpg",
      "/docs/assets/images/teams/alfaromeo/alr14.jpg",
      "/docs/assets/images/teams/alfaromeo/alr15.jpg",
    ],
  },
  WILLIAMS: {
    logo: Logo.williams,
    name: "Williams Racing",
    fullname: "Williams Racing",
    car: Car.williams,
    drivers: [
      getDriverByKey(DriverKey.george_russell),
      getDriverByKey(DriverKey.nicholas_latifi),
    ],
    base: "Гроув, Великобритания",
    teamChief: "Фрэнк Уильямс/Клэр Уильямс",
    powerUnit: "Mercedes",
    chassis: "FW43",
    firstTeamEntry: 1978,
    worldChampionships: "1980, 1982, 1987, 1992, 1993, 1996, 1997",
    constructorsСup: "1980, 1981, 1986, 1987, 1992-1994, 1996, 1997",
    highestRaceFinish: "1 (x114)",
    polePositions: 129,
    fastestLaps: 133,
    info2019: "<p>2019</p>" + "<p>...</p>",
    info2018: "<p>...</p>" + "<p>...</p>",
    info2017: "<p>...</p>" + "<p>...</p>",
    info2016: "<p>...</p>" + "<p>...</p>",
    images: [
      "/docs/assets/images/teams/williams/wil1.jpg",
      "/docs/assets/images/teams/williams/wil2.jpg",
      "/docs/assets/images/teams/williams/wil3.jpg",
      "/docs/assets/images/teams/williams/wil4.jpg",
      "/docs/assets/images/teams/williams/wil5.jpg",
      "/docs/assets/images/teams/williams/wil6.jpg",
      "/docs/assets/images/teams/williams/wil7.jpg",
      "/docs/assets/images/teams/williams/wil8.jpg",
      "/docs/assets/images/teams/williams/wil9.jpg",
      "/docs/assets/images/teams/williams/wil10.jpg",
      "/docs/assets/images/teams/williams/wil11.jpg",
      "/docs/assets/images/teams/williams/wil12.jpg",
      "/docs/assets/images/teams/williams/wil13.jpg",
      "/docs/assets/images/teams/williams/wil14.jpg",
      "/docs/assets/images/teams/williams/wil15.jpg",
    ],
  },
};

export const TeamKeys = Object.keys(Teams);
