export const getPilots = (year) => {
  if (2019 == year) {
    return pilots2019;
  } else if (2018 == year) {
    return pilots2018;
  } else {
    return pilots2020;
  }
};

const pilots2020 = [
  {
    number: 7,
    name: "Kimi Räikkönen",
    season: 17,
    team: "Alfa Romeo",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 44,
    name: "Lewis Hamilton",
    season: 13,
    team: "Mercedes",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 5,
    name: "Sebastian Vettel",
    season: 13,
    team: "Ferrari",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 11,
    name: "Sergio Perez",
    season: 9,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 3,
    name: "Daniel Ricciardo",
    season: 9,
    team: "Renault",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 80,
    name: "Romain Grosjean",
    season: 9,
    team: "Haas",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 77,
    name: "Valtteri Bottas",
    season: 7,
    team: "Mercedes",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 20,
    name: "Kevin Magnussen",
    season: 6,
    team: "Haas",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 26,
    name: "Daniil Kvyat",
    season: 5,
    team: "Alpha Tauri",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 33,
    name: "Max Verstappen",
    season: 5,
    team: "Red Bull Racing",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 55,
    name: "Carlos Sainz",
    season: 5,
    team: "McLaren",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 10,
    name: "Pier Gasli",
    season: 3,
    team: "Alpha Tauri",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 18,
    name: "Lance Stroll",
    season: 3,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 31,
    name: "Esteban Ocon",
    season: 3,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 99,
    name: "Antonio Giovinazzi",
    season: 2,
    team: "Alfa Romeo",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 16,
    name: "Charles Leclerc",
    season: 2,
    team: "Ferrari",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 63,
    name: "George Russell",
    season: 1,
    team: "Williams",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 4,
    name: "Lando Norris",
    season: 1,
    team: "McLaren",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 23,
    name: "Alexander Albon",
    season: 1,
    team: "Red Bull Racing",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 6,
    name: "Nicholas Latifi",
    season: 0,
    team: "Williams",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
];

const pilots2019 = [
  {
    number: 7,
    name: "Kimi Räikkönen",
    season: 17,
    team: "Alfa Romeo",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 44,
    name: "Lewis Hamilton",
    season: 13,
    team: "Mercedes",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 5,
    name: "Sebastian Vettel",
    season: 13,
    team: "Ferrari",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 11,
    name: "Sergio Perez",
    season: 9,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 3,
    name: "Daniel Ricciardo",
    season: 9,
    team: "Renault",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 80,
    name: "Romain Grosjean",
    season: 9,
    team: "Haas",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 77,
    name: "Valtteri Bottas",
    season: 7,
    team: "Mercedes",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 20,
    name: "Kevin Magnussen",
    season: 6,
    team: "Haas",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 26,
    name: "Daniil Kvyat",
    season: 5,
    team: "Alpha Tauri",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 33,
    name: "Max Verstappen",
    season: 5,
    team: "Red Bull Racing",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 55,
    name: "Carlos Sainz",
    season: 5,
    team: "McLaren",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 10,
    name: "Pier Gasli",
    season: 3,
    team: "Alpha Tauri",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 18,
    name: "Lance Stroll",
    season: 3,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 31,
    name: "Esteban Ocon",
    season: 3,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 99,
    name: "Antonio Giovinazzi",
    season: 2,
    team: "Alfa Romeo",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 16,
    name: "Charles Leclerc",
    season: 2,
    team: "Ferrari",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 63,
    name: "George Russell",
    season: 1,
    team: "Williams",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 4,
    name: "Lando Norris",
    season: 1,
    team: "McLaren",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 23,
    name: "Alexander Albon",
    season: 1,
    team: "Red Bull Racing",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 6,
    name: "Nicholas Latifi",
    season: 0,
    team: "Williams",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
];

const pilots2018 = [
  {
    number: 7,
    name: "Kimi Räikkönen",
    season: 17,
    team: "Alfa Romeo",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 44,
    name: "Lewis Hamilton",
    season: 13,
    team: "Mercedes",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 5,
    name: "Sebastian Vettel",
    season: 13,
    team: "Ferrari",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 11,
    name: "Sergio Perez",
    season: 9,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 3,
    name: "Daniel Ricciardo",
    season: 9,
    team: "Renault",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 80,
    name: "Romain Grosjean",
    season: 9,
    team: "Haas",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 77,
    name: "Valtteri Bottas",
    season: 7,
    team: "Mercedes",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 20,
    name: "Kevin Magnussen",
    season: 6,
    team: "Haas",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 26,
    name: "Daniil Kvyat",
    season: 5,
    team: "Alpha Tauri",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 33,
    name: "Max Verstappen",
    season: 5,
    team: "Red Bull Racing",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 55,
    name: "Carlos Sainz",
    season: 5,
    team: "McLaren",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 10,
    name: "Pier Gasli",
    season: 3,
    team: "Alpha Tauri",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 18,
    name: "Lance Stroll",
    season: 3,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 31,
    name: "Esteban Ocon",
    season: 3,
    team: "Racing Point",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 99,
    name: "Antonio Giovinazzi",
    season: 2,
    team: "Alfa Romeo",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 16,
    name: "Charles Leclerc",
    season: 2,
    team: "Ferrari",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 63,
    name: "George Russell",
    season: 1,
    team: "Williams",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 4,
    name: "Lando Norris",
    season: 1,
    team: "McLaren",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 23,
    name: "Alexander Albon",
    season: 1,
    team: "Red Bull Racing",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    number: 6,
    name: "Nicholas Latifi",
    season: 0,
    team: "Williams",
    score: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
];
