import { DriverKey, getDriverByKey } from "../driver/drivers-data";

export const getPilots = (year) => {
  if (2019 == year) {
    return pilots2019;
  } else if (2018 == year) {
    return pilots2018;
  } else {
    return pilots2020;
  }
};

const pilotsAll = [
  {
    driver: getDriverByKey(DriverKey.kimi_raikkonen),
    number: 7,
    name: "Kimi Raikkonen",
    season: 17,
    team: "Alfa Romeo",
    points: 1859,
    poles: 18,
    bestLap: 46,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.lewis_hamilton),
    number: 44,
    name: "Lewis Hamilton",
    season: 13,
    team: "Mercedes",
    points: 3431,
    poles: 88,
    bestLap: 47,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.sebastian_vettel),
    number: 5,
    name: "Sebastian Vettel",
    season: 13,
    team: "Ferrari",
    points: 2985,
    poles: 57,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.sergio_perez),
    number: 11,
    name: "Sergio Perez",
    season: 9,
    team: "Racing Point",
    points: 581,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.daniel_ricciardo),
    number: 3,
    name: "Daniel Ricciardo",
    season: 9,
    team: "Renault",
    points: 1040,
    poles: 3,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.romain_grosjean),
    number: 8,
    name: "Romain Grosjean",
    season: 9,
    team: "Haas",
    points: 389,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.nico_hulkenberg),
    number: 8,
    name: "Nico Hulkenberg",
    season: 9,
    team: "Renault",
    points: 37,
    poles: 1,
    bestLap: 2,
    podiums: 0,
    laps: 9038,
  },
  {
    driver: getDriverByKey(DriverKey.valtteri_bottas),
    number: 77,
    name: "Valtteri Bottas",
    season: 7,
    team: "Mercedes",
    points: 1289,
    poles: 11,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.kevin_magnussen),
    number: 20,
    name: "Kevin Magnussen",
    season: 6,
    team: "Haas",
    points: 157,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.daniil_kvyat),
    number: 26,
    name: "Daniil Kvyat",
    season: 5,
    team: "Alpha Tauri",
    points: 170,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.max_verstappen),
    number: 33,
    name: "Max Verstappen",
    season: 5,
    team: "Red Bull Racing",
    points: 948,
    poles: 2,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.carlos_sainz),
    number: 55,
    name: "Carlos Sainz",
    season: 5,
    team: "McLaren",
    points: 267,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.pier_gasli),
    number: 10,
    name: "Pier Gasli",
    season: 3,
    team: "Alpha Tauri",
    points: 124,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.lance_stroll),
    number: 18,
    name: "Lance Stroll",
    season: 3,
    team: "Racing Point",
    points: 67,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.esteban_ocon),
    number: 31,
    name: "Esteban Ocon",
    season: 3,
    team: "Racing Point",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.antonio_giovinazzi),
    number: 99,
    name: "Antonio Giovinazzi",
    season: 2,
    team: "Alfa Romeo",
    points: 14,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.charles_leclerc),
    number: 16,
    name: "Charles Leclerc",
    season: 2,
    team: "Ferrari",
    points: 303,
    poles: 7,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.george_russell),
    number: 63,
    name: "George Russell",
    season: 1,
    team: "Williams",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.lando_norris),
    number: 4,
    name: "Lando Norris",
    season: 1,
    team: "McLaren",
    points: 49,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.alexander_albon),
    number: 23,
    name: "Alexander Albon",
    season: 1,
    team: "Red Bull Racing",
    points: 92,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.nicholas_latifi),
    number: 6,
    name: "Nicholas Latifi",
    season: 0,
    team: "Williams",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
];

const pilots2020 = [
  {
    driver: getDriverByKey(DriverKey.kimi_raikkonen),
    number: 7,
    name: "Kimi Raikkonen",
    season: 17,
    team: "Alfa Romeo",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.lewis_hamilton),
    number: 44,
    name: "Lewis Hamilton",
    season: 13,
    team: "Mercedes",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.sebastian_vettel),
    number: 5,
    name: "Sebastian Vettel",
    season: 13,
    team: "Ferrari",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.sergio_perez),
    number: 11,
    name: "Sergio Perez",
    season: 9,
    team: "Racing Point",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.daniel_ricciardo),
    number: 3,
    name: "Daniel Ricciardo",
    season: 9,
    team: "Renault",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.romain_grosjean),
    number: 8,
    name: "Romain Grosjean",
    season: 9,
    team: "Haas",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.valtteri_bottas),
    number: 77,
    name: "Valtteri Bottas",
    season: 7,
    team: "Mercedes",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.kevin_magnussen),
    number: 20,
    name: "Kevin Magnussen",
    season: 6,
    team: "Haas",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.daniil_kvyat),
    number: 26,
    name: "Daniil Kvyat",
    season: 5,
    team: "Alpha Tauri",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.max_verstappen),
    number: 33,
    name: "Max Verstappen",
    season: 5,
    team: "Red Bull Racing",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.carlos_sainz),
    number: 55,
    name: "Carlos Sainz",
    season: 5,
    team: "McLaren",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.pier_gasli),
    number: 10,
    name: "Pier Gasli",
    season: 3,
    team: "Alpha Tauri",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.lance_stroll),
    number: 18,
    name: "Lance Stroll",
    season: 3,
    team: "Racing Point",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.esteban_ocon),
    number: 31,
    name: "Esteban Ocon",
    season: 3,
    team: "Racing Point",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.antonio_giovinazzi),
    number: 99,
    name: "Antonio Giovinazzi",
    season: 2,
    team: "Alfa Romeo",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.charles_leclerc),
    number: 16,
    name: "Charles Leclerc",
    season: 2,
    team: "Ferrari",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.george_russell),
    number: 63,
    name: "George Russell",
    season: 1,
    team: "Williams",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.lando_norris),
    number: 4,
    name: "Lando Norris",
    season: 1,
    team: "McLaren",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.alexander_albon),
    number: 23,
    name: "Alexander Albon",
    season: 1,
    team: "Red Bull Racing",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
  {
    driver: getDriverByKey(DriverKey.nicholas_latifi),
    number: 6,
    name: "Nicholas Latifi",
    season: 0,
    team: "Williams",
    points: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: 0,
  },
];

const pilots2019 = [
  {
    driver: getDriverByKey(DriverKey.lewis_hamilton),
    number: 44,
    name: "Lewis Hamilton",
    season: 13,
    team: "Mercedes",
    points: 413,
    victory: 11,
    poles: 5,
    bestLap: 6,
    podiums: 17,
    laps: "???",
    position: 1,
  },
  {
    driver: getDriverByKey(DriverKey.valtteri_bottas),
    number: 77,
    name: "Valtteri Bottas",
    season: 7,
    team: "Mercedes",
    points: 326,
    victory: 4,
    poles: 5,
    bestLap: 3,
    podiums: 15,
    laps: "???",
    position: 2,
  },
  {
    driver: getDriverByKey(DriverKey.max_verstappen),
    number: 33,
    name: "Max Verstappen",
    season: 5,
    team: "Red Bull Racing",
    points: 278,
    victory: 3,
    poles: 3,
    bestLap: 3,
    podiums: 9,
    laps: "???",
    position: 3,
  },
  {
    driver: getDriverByKey(DriverKey.charles_leclerc),
    number: 16,
    name: "Charles Leclerc",
    season: 2,
    team: "Ferrari",
    points: 264,
    victory: 0,
    poles: 6,
    bestLap: 4,
    podiums: 10,
    laps: "???",
    position: 4,
  },
  {
    driver: getDriverByKey(DriverKey.sebastian_vettel),
    number: 5,
    name: "Sebastian Vettel",
    season: 13,
    team: "Ferrari",
    points: 240,
    victory: 1,
    poles: 2,
    bestLap: 2,
    podiums: 9,
    laps: "???",
    position: 5,
  },
  {
    driver: getDriverByKey(DriverKey.carlos_sainz),
    number: 55,
    name: "Carlos Sainz",
    season: 5,
    team: "McLaren",
    points: 96,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 1,
    laps: "???",
    position: 6,
  },
  {
    driver: getDriverByKey(DriverKey.pier_gasli),
    number: 10,
    name: "Pier Gasli",
    season: 3,
    team: "Red Bull / Toro Rosso",
    points: 95,
    victory: 1,
    poles: 0,
    bestLap: 2,
    podiums: 1,
    laps: "???",
    position: 7,
  },
  {
    driver: getDriverByKey(DriverKey.alexander_albon),
    number: 23,
    name: "Alexander Albon",
    season: 1,
    team: "Toro Rosso / Red Bull",
    points: 92,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 8,
  },
  {
    driver: getDriverByKey(DriverKey.daniel_ricciardo),
    number: 3,
    name: "Daniel Ricciardo",
    season: 9,
    team: "Renault",
    points: 54,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 9,
  },
  {
    driver: getDriverByKey(DriverKey.sergio_perez),
    number: 11,
    name: "Sergio Perez",
    season: 9,
    team: "Racing Point",
    points: 52,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 10,
  },
  {
    driver: getDriverByKey(DriverKey.lando_norris),
    number: 4,
    name: "Lando Norris",
    season: 1,
    team: "McLaren",
    points: 49,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 11,
  },
  {
    driver: getDriverByKey(DriverKey.kimi_raikkonen),
    number: 7,
    name: "Kimi Raikkonen",
    season: 17,
    team: "Alfa Romeo",
    points: 43,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 12,
  },
  {
    driver: getDriverByKey(DriverKey.daniil_kvyat),
    number: 26,
    name: "Daniil Kvyat",
    season: 5,
    team: "Toro Rosso",
    points: 43,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 1,
    laps: "???",
    position: 13,
  },
  {
    driver: getDriverByKey(DriverKey.nico_hulkenberg),
    number: 27,
    name: "Nico Hulkenberg",
    season: 9,
    team: "Renault",
    points: 37,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 14,
  },
  {
    driver: getDriverByKey(DriverKey.lance_stroll),
    number: 18,
    name: "Lance Stroll",
    season: 3,
    team: "Racing Point",
    points: 21,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 15,
  },
  {
    driver: getDriverByKey(DriverKey.kevin_magnussen),
    number: 20,
    name: "Kevin Magnussen",
    season: 6,
    team: "Haas",
    points: 20,
    victory: 0,
    poles: 0,
    bestLap: 1,
    podiums: 0,
    laps: "???",
    position: 16,
  },
  {
    driver: getDriverByKey(DriverKey.antonio_giovinazzi),
    number: 99,
    name: "Antonio Giovinazzi",
    season: 2,
    team: "Alfa Romeo",
    points: 14,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 17,
  },
  {
    driver: getDriverByKey(DriverKey.romain_grosjean),
    number: 8,
    name: "Romain Grosjean",
    season: 9,
    team: "Haas",
    points: 8,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 18,
  },
  {
    driver: getDriverByKey(DriverKey.robert_kubica),
    number: 88,
    name: "Robert Kubica",
    season: 6,
    team: "Williams",
    points: 1,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 19,
  },
  {
    driver: getDriverByKey(DriverKey.george_russell),
    number: 63,
    name: "George Russell",
    season: 1,
    team: "Williams",
    points: 0,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 20,
  },
];

const pilots2018 = [
  {
    driver: getDriverByKey(DriverKey.lewis_hamilton),
    number: 44,
    name: "Lewis Hamilton",
    season: 12,
    team: "Mercedes",
    points: 408,
    victory: 11,
    poles: 11,
    bestLap: 3,
    podiums: 17,
    laps: "???",
    position: 1,
  },
  {
    driver: getDriverByKey(DriverKey.sebastian_vettel),
    number: 5,
    name: "Sebastian Vettel",
    season: 12,
    team: "Ferrari",
    points: 320,
    poles: 2,
    bestLap: 2,
    podiums: 9,
    laps: "???",
    position: 2,
  },
  {
    driver: getDriverByKey(DriverKey.kimi_raikkonen),
    number: 7,
    name: "Kimi Raikkonen",
    season: 17,
    team: "Ferrari",
    points: 251,
    victory: 1,
    poles: 1,
    bestLap: 1,
    podiums: 12,
    laps: "???",
    position: 3,
  },
  {
    driver: getDriverByKey(DriverKey.max_verstappen),
    number: 33,
    name: "Max Verstappen",
    season: 4,
    team: "Red Bull Racing",
    points: 249,
    victory: 2,
    poles: 0,
    bestLap: 2,
    podiums: 11,
    laps: "???",
    position: 4,
  },
  {
    driver: getDriverByKey(DriverKey.valtteri_bottas),
    number: 77,
    name: "Valtteri Bottas",
    season: 6,
    team: "Mercedes",
    points: 247,
    victory: 0,
    poles: 2,
    bestLap: 7,
    podiums: 8,
    laps: "???",
    position: 5,
  },
  {
    driver: getDriverByKey(DriverKey.daniel_ricciardo),
    number: 3,
    name: "Daniel Ricciardo",
    season: 8,
    team: "Red Bull Racing",
    points: 170,
    victory: 2,
    poles: 2,
    bestLap: 4,
    podiums: 2,
    laps: "???",
    position: 6,
  },
  {
    driver: getDriverByKey(DriverKey.nico_hulkenberg),
    number: 8,
    name: "Nico Hulkenberg",
    season: 8,
    team: "Renault",
    points: 69,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 7,
  },
  {
    driver: getDriverByKey(DriverKey.sergio_perez),
    number: 11,
    name: "Sergio Perez",
    season: 8,
    team: "Force India",
    points: 62,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 1,
    laps: "???",
    position: 8,
  },
  {
    driver: getDriverByKey(DriverKey.kevin_magnussen),
    number: 20,
    name: "Kevin Magnussen",
    season: 5,
    team: "Haas",
    points: 56,
    victory: 0,
    poles: 0,
    bestLap: 1,
    podiums: 0,
    laps: "???",
    position: 9,
  },
  {
    driver: getDriverByKey(DriverKey.carlos_sainz),
    number: 55,
    name: "Carlos Sainz",
    season: 4,
    team: "Renault",
    points: 53,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 10,
  },
  {
    driver: getDriverByKey(DriverKey.fernando_alonso),
    number: 29,
    name: "Fernando Alonso",
    season: 17,
    team: "McLaren",
    points: 50,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 11,
  },
  {
    driver: getDriverByKey(DriverKey.esteban_ocon),
    number: 31,
    name: "Esteban Ocon",
    season: 3,
    team: "Force India",
    points: 49,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 12,
  },
  {
    driver: getDriverByKey(DriverKey.charles_leclerc),
    number: 16,
    name: "Charles Leclerc",
    season: 1,
    team: "Sauber",
    points: 39,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 13,
  },
  {
    driver: getDriverByKey(DriverKey.romain_grosjean),
    number: 8,
    name: "Romain Grosjean",
    season: 8,
    team: "Haas",
    points: 37,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 14,
  },
  {
    driver: getDriverByKey(DriverKey.pier_gasli),
    number: 10,
    name: "Pier Gasli",
    season: 2,
    team: "Toro Rosso",
    points: 29,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 15,
  },
  {
    driver: getDriverByKey(DriverKey.stoffel_vandoorne),
    number: 2,
    name: "Stoffel Vandoorne",
    season: 3,
    team: "McLaren",
    points: 12,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 16,
  },
  {
    driver: getDriverByKey(DriverKey.marcus_ericsson),
    number: 9,
    name: "Marcus Ericsson",
    season: 5,
    team: "Sauber",
    points: 9,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 17,
  },
  {
    driver: getDriverByKey(DriverKey.lance_stroll),
    number: 18,
    name: "Lance Stroll",
    season: 3,
    team: "Williams",
    points: 6,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 18,
  },
  {
    driver: getDriverByKey(DriverKey.brendon_hartley),
    number: 28,
    name: "Brendon Hartley",
    season: 2,
    team: "Toro Rosso",
    points: 4,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 19,
  },
  {
    driver: getDriverByKey(DriverKey.sergey_sirotkin),
    number: 35,
    name: "Sergey Sirotkin",
    season: 1,
    team: "Williams",
    points: 1,
    victory: 0,
    poles: 0,
    bestLap: 0,
    podiums: 0,
    laps: "???",
    position: 20,
  },
];
